AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db//**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'spec/factories/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
