AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'db//**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'spec/factories/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation